services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        # CRITICAL: Replace this with your actual server's public IP or Domain name!
        # Remember, it MUST use https:// if you want webcam permissions to work.
        - VITE_API_BASE=https://your-domain-or-ip.com:8000
    ports:
      - "3000:3000"
    restart: always
    Sdepends_on:
      - backendS